# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51db35891bf2af34293f0a7861e89fa42ee587d554a105240165e324f134f295507018d1a4cca2b7c0178c478008cbcfcf2025c11fd6748608cd12ba89de87e7

test:
  secret_key_base: a0d65e76e9db393a9b557d3103f672313ebd41020a249aad9800bd7c59d0c1c89243432304663ebb9297a1150bc9215b8353ae7a1a110e6503253b3ce4d4c75e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
